# Generated by Django 6.0.2 on 2026-02-15 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=3, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(max_length=100)),
                ('mouth_size', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('current_quantity', models.IntegerField()),
                ('supplied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyInventoryApp.supplier')),
            ],
        ),
    ]
