# Generated by Django 6.0.2 on 2026-02-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0002_waterbottle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='sku',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
