# Generated by Django 6.0.1 on 2026-04-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapasapp', '0002_account_alter_dish_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
